import { GenderType } from "@/api/user/user.types";
import { UserState } from "./userReducer.types";
export declare const userInitialState: UserState;
export declare const user: import("@reduxjs/toolkit").Slice<UserState, {
    onUserDetailsFetch: (state: {
        userDetails: {
            lead_id: string;
            user_type: import("@/api/user/user.types").UserRoles | "";
            country_code: string;
            registration_credit: boolean;
            registration_credit_amount: number;
            leads_status: number;
            token: string;
        };
        profile: {
            address_id: null | number;
            bank_account_no: string;
            bank_branch: string;
            bank_name: string;
            comments: string;
            created_at: string;
            date_of_birth: string;
            email: string;
            formatted_id: string;
            full_name: string;
            gender: GenderType;
            healthcondition: any[];
            healthtopic: any[];
            id: string;
            is_aia_downgraded: boolean;
            lead_owner_id: number;
            lead_type: string;
            leads_status: number;
            mobile_no: string;
            name: string;
            name_title: string | null;
            nic_no: string;
            offer_notification: null | string;
            organization_id: number;
            phone: null | string;
            preferred_language: null | string;
            product_code?: string | null | undefined;
            profile_picture_url: string;
            request_quote_notification: null | number;
            role: string;
            show_on_leadboard: number;
            show_to_doner: number;
            source: number;
            trial_used: string;
            updated_at: string;
            userDetail: string;
            store_id: string;
        };
    }, { payload }: {
        payload: any;
        type: string;
    }) => void;
    onProfileFetch: (state: {
        userDetails: {
            lead_id: string;
            user_type: import("@/api/user/user.types").UserRoles | "";
            country_code: string;
            registration_credit: boolean;
            registration_credit_amount: number;
            leads_status: number;
            token: string;
        };
        profile: {
            address_id: null | number;
            bank_account_no: string;
            bank_branch: string;
            bank_name: string;
            comments: string;
            created_at: string;
            date_of_birth: string;
            email: string;
            formatted_id: string;
            full_name: string;
            gender: GenderType;
            healthcondition: any[];
            healthtopic: any[];
            id: string;
            is_aia_downgraded: boolean;
            lead_owner_id: number;
            lead_type: string;
            leads_status: number;
            mobile_no: string;
            name: string;
            name_title: string | null;
            nic_no: string;
            offer_notification: null | string;
            organization_id: number;
            phone: null | string;
            preferred_language: null | string;
            product_code?: string | null | undefined;
            profile_picture_url: string;
            request_quote_notification: null | number;
            role: string;
            show_on_leadboard: number;
            show_to_doner: number;
            source: number;
            trial_used: string;
            updated_at: string;
            userDetail: string;
            store_id: string;
        };
    }, { payload }: {
        payload: any;
        type: string;
    }) => void;
    onRemoveUserDetails: (state: {
        userDetails: {
            lead_id: string;
            user_type: import("@/api/user/user.types").UserRoles | "";
            country_code: string;
            registration_credit: boolean;
            registration_credit_amount: number;
            leads_status: number;
            token: string;
        };
        profile: {
            address_id: null | number;
            bank_account_no: string;
            bank_branch: string;
            bank_name: string;
            comments: string;
            created_at: string;
            date_of_birth: string;
            email: string;
            formatted_id: string;
            full_name: string;
            gender: GenderType;
            healthcondition: any[];
            healthtopic: any[];
            id: string;
            is_aia_downgraded: boolean;
            lead_owner_id: number;
            lead_type: string;
            leads_status: number;
            mobile_no: string;
            name: string;
            name_title: string | null;
            nic_no: string;
            offer_notification: null | string;
            organization_id: number;
            phone: null | string;
            preferred_language: null | string;
            product_code?: string | null | undefined;
            profile_picture_url: string;
            request_quote_notification: null | number;
            role: string;
            show_on_leadboard: number;
            show_to_doner: number;
            source: number;
            trial_used: string;
            updated_at: string;
            userDetail: string;
            store_id: string;
        };
    }) => void;
}, "user", "user", import("@reduxjs/toolkit").SliceSelectors<UserState>>;
export declare const onUserDetailsFetch: import("@reduxjs/toolkit").ActionCreatorWithPayload<any, "user/onUserDetailsFetch">, onRemoveUserDetails: import("@reduxjs/toolkit").ActionCreatorWithoutPayload<"user/onRemoveUserDetails">, onProfileFetch: import("@reduxjs/toolkit").ActionCreatorWithPayload<any, "user/onProfileFetch">;
declare const _default: import("redux").Reducer<UserState>;
export default _default;
