export enum AppRoute {
  Login = "/login",
  SignUp = "/sign-up",
  // Dashboard = "/",
  Claim = "/claim",
  Employees = "/employees",
  EmployeeDetails = "/employees/:employeeId",
  Transaction = "/transaction",
  Support = "/support",
  Billing = "/billing",
  ActivityLog = "/activity-log",
  Dashboard = "/dashboard",
  LeaderBoard = "/leaderboard",
  Consultations = "/consultations",
  Appointments = "/appointments",
  Patients = "/patients",
  PatientDetails = "/patients/:leadId",
  ConsultationDetails = "/consultations/:consultationId",
}
